brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
autoCreateTopicEnable=true
# 必须改成运行 RocketMQ 的机器局域网 IP（producer/consumer 跨机连接 broker 的地址）
brokerIP1=10.21.76.221
